SELECT M.YEAR, (M.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV , D.ID
FROM ECOLI_DATA D
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(D.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV
